[package]
name = "parsers"
description = "Parser combinators library"
version = "0.3.4"
authors = ["nanolsn <nanonicholson@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nanolsn/parsers"
keywords = ["parser"]

[dependencies]
